### ISSUE TITLE
Humble request for more explanation of how to use the script

### ISSUE THREAD

**Issue by edurojasr** [andrewharvey/osm-editor-layer-index-qgis#2]
Hello Andrew

I am a QGIS enthusiast and an advanced user, with some knowledge in software development and programming, I see that this script needs Node.js.

I ask you humbly if you can explain more the use of the script or do a little tutorial maybe? I suspect I must have the cloned git of editor-layer-index to be able to use this script but I'm not sure.

As I said, I'm just a QGIS user who wants access to the layer index editor for more information.

Thank you

**Comment by andrewharvey** [comment]
@eduardosoltig Check the README at https://github.com/andrewharvey/osm-editor-layer-index-qgis/blob/master/README.md for installation and usage instructions.

You can either "Install and use globally" or "Install and use locally", both options you'll need to install Node.js, then just run the command lines from the README. If you face a specific issue, feel free to comment here.

Only install and use locally needs the repo cloned, and that step is shown in the README.

`imagery.geojson` comes from https://github.com/osmlab/editor-layer-index/

I think it would be helpful to build the QGIS index file automatically here so you could just download it, but I'm just not sure the best way for editor-layer-index to trigger a rebuild here without embedding this as part of editor-layer-index.

**Comment by edurojasr** [comment]
Thanks for the help Andrew

I already installed Node.js on windows 10 and I'm trying to use it from powershell (I do not know if this is my problem) 

then I use:
   `npm install -g osm-editor-layer-index-qgis` (globally)

check for the package version usign 
   `npm view <package-name> version`

return
  osm-editor-layer-index-qgis@1.0.1 

Now from inside Node.js
Im using 
`osm-editor-layer-index-qgis [-c AU,NZ,..] < imagery.geojson > imagery.xml`

return

osm-editor-layer-index-qgis [-c AU,NZ,..] < imagery.geojson > imagery.xml
Thrown:
osm-editor-layer-index-qgis [-c AU,NZ,..] < imagery.geojson > imagery.xml
                                                    ^^

SyntaxError: Unexpected identifier

the symbols ^^ are below the "AU"

I have dowloaded the imagery.geojson from https://github.com/osmlab/editor-layer-index/blob/gh-pages/imagery.geojson and placed in the package folder (node_modules\osm-editor-layer-index-qgis)

I have the suspicion that I am very lost of how to use the script from Node.js in windows in the powershell, I do not know if I should define the directories or other steps to make proper use of the script

**Comment by andrewharvey** [comment]
Right so it looks like you've managed to install it. But "Now from inside Node.js"... This shouldn't be run inside node, since it's the command line used to run the program, not JavaScript to execute.

So outside Node in your shell just run:

osm-editor-layer-index-qgis -c US < imagery.geojson > imagery.xml

I don't know powershell so I'm not sure if those stdin/stout redirectors will work. Might be easier to run a linux subshell for windows.

imagery.geojson should be placed in your current directory that you execute the script from.

Alternatively I ran it globally so you could just download this...

[OSM_Imagery.zip](https://github.com/andrewharvey/osm-editor-layer-index-qgis/files/2902904/OSM_Imagery.zip)

**Comment by edurojasr** [comment]
Andrew

my rookie mistake was to try use the standard input \ output in Windows PowerShell as if it were in Unix systems with Bash, that's why the script did not work, I apologize

I should have used something similar to `Get-Content input.txt | ./program> output.txt`

But also thank you very much for your help and time.

I'm going to try to use the linux subsystem for windows (WSL)

**Comment by edurojasr** [comment]
tested with WSL and it worked!

 thanks for your help and your patience

**Comment by andrewharvey** [comment]
Great, if there's anything you think that would have helped make this easier please let me know.
